version: '3'
services:
  db:
    image: 'mysql:latest'
    environment:
      MYSQL_ROOT_PASSWORD: 'localhost'
    ports: 
      - '3906:3306'
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    command: sh -c "npm start"
  backend:
    build:
      context: ./backend
    ports:
      - "8001:8001"
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8001"
